# -*- coding: utf-8 -*-
"""Complexity Analysis Graphipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ab7j6kHAiiIGio-y2M3Gtu4anchIQDWJ
"""

import matplotlib.pyplot as plt
import numpy as np

n = np.arange(1, 101)
operations = n  # O(n)

plt.figure(figsize=(10, 6))
plt.plot(n, operations, label="O(n) Time Complexity", color='green', linewidth=2)
plt.title("O(n) Time Complexity", fontsize=14)
plt.xlabel("Input Size (n)", fontsize=12)
plt.ylabel("Operations Count", fontsize=12)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("o_n_time_complexity.jpg", dpi=300)
plt.show()

n = np.arange(1, 101)
space_used = np.ones_like(n)  # O(1)

plt.figure(figsize=(10, 6))
plt.plot(n, space_used, label="O(1) Space Complexity", color='blue', linewidth=2)
plt.title("O(1) Space Complexity", fontsize=14)
plt.xlabel("Input Size (n)", fontsize=12)
plt.ylabel("Space Used", fontsize=12)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("o_1_space_complexity.jpg", dpi=300)
plt.show()